spring.application.name=DFSS
spring.security.user.name=user
# Maximum size allowed for a single uploaded file
spring.servlet.multipart.max-file-size=100MB

# Maximum total request size allowed for multipart/form-data
spring.servlet.multipart.max-request-size=100MB
storage.path=/home/frog/Documents/Distributed System/DFSS (1)/DFSS/Storage/Output/
total.nodes=3
chunk.size=1024*1024


spring.datasource.url=jdbc:postgresql://localhost:5432/dfss
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true